[2024-07-09 15:03:33,020] [DEBUG] 发送:4344a500000000
[2024-07-09 15:03:33,021] [DEBUG] 等待读取数据...
[2024-07-09 15:03:33,084] [DEBUG] 收到:5253a500000e56312e315f323032343032303200
[2024-07-09 15:03:33,085] [DEBUG] 串口已连接，通信正常
[2024-07-09 15:03:33,086] [DEBUG] 等待读取huk或判断指令...
[2024-07-09 15:04:04,150] [DEBUG] 发送:4344a500000000
[2024-07-09 15:04:04,150] [DEBUG] 等待读取数据...
[2024-07-09 15:04:04,222] [DEBUG] 收到:5253a500000e56312e315f323032343032303200
[2024-07-09 15:04:04,222] [DEBUG] 串口已连接，通信正常
[2024-07-09 15:04:04,223] [DEBUG] 等待读取huk或判断指令...
[2024-07-09 15:04:07,489] [DEBUG] 收到huk或判断指令:5253b30b0000
[2024-07-09 15:04:07,489] [DEBUG] COM位1 kr烧入失败 次数1
[2024-07-09 15:04:07,502] [DEBUG] 烧入总次数1
[2024-07-09 15:04:07,503] [DEBUG] --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[2024-07-09 15:04:08,061] [DEBUG] 等待读取huk或判断指令...
[2024-07-09 15:04:27,796] [DEBUG] 收到huk或判断指令:None
[2024-07-09 15:04:27,796] [DEBUG] [2024-07-09 15:04:27.796254] 停止读取数据
[2024-07-09 15:04:27,796] [ERROR] 错误：停止读取数据
Traceback (most recent call last):
  File "D:\NEW\zfb_tools_旧\zfb_tools\burn_tool\kp_send_recive\KP_send_receive.py", line 117, in Start_send
    self.Data_dispose()  # 进入Kr烧入循环
    ^^^^^^^^^^^^^^^^^^^
  File "D:\NEW\zfb_tools_旧\zfb_tools\burn_tool\kp_send_recive\KP_send_receive.py", line 221, in Data_dispose
    raise Exception("停止读取数据") #抛出没有数据的错误
    ^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: 停止读取数据
